apiVersion: v1
kind: PersistentVolume
metadata:
  name: local
  labels:
    types: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Mi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /meubanco/

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
        - image: williameiji/kubs-database:1.0
          name: mysql
          ports:
            - containerPort: 3306
              name: mysql

          volumeMounts:
            - name: local
              mountPath: /var/lib/mysql
      volumes:
        - name: local
          persistentVolumeClaim:
            claimName: local

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
  labels:
    app: php
spec:
  selector:
    matchLabels:
      app: php
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
        - name: php
          image: williameiji/kubs-php-app:1.0
          imagePullPolicy: Always
          ports:
            - containerPort: 80
